version: "3.9"
services:
  api:
    build: 
      context: ./api
      dockerfile: ./Dockerfile.api
    volumes:
      - ./api:/usr/src/app/
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - mongodb
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${API_PORT}

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017"
    volumes:
      - data:/bitnami/mongodb

  web:
    restart: on-failure
    build:
      context: ./web
      dockerfile: ./Dockerfile.web
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - 24678:24678
    volumes:
      - ./web:/usr/src/app/
      - /usr/src/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port ${WEB_PORT}

volumes:
  data:
